# Winter Holidays Review
# Author: Dulneth
# 8 January 2024

# Requirements:
#  - create a function called winter_holiday()
#  - take one parameter
#      - string
#  - return a summary of an event from your holidays


import random


def winter_holiday(good_or_bad: str) -> str:
    """Give a summary of our winter holidays 2023/24

    Params:
        good_or_bad - indicate what kind of event to summarize

    Returns:
        an event that happened during the holidays
        the event is selected randomly"""

    import random

def holiday_summary(good_or_bad):
    good_events = ["Received better gifts", "Went on trips", "Had fun with freinds and family members"]
    bad_events = ["Missed a party"]

    if good_or_bad.lower() == 'good':
        return random.choice(good_events)
    elif good_or_bad.lower() == 'bad':
        return random.choice(bad_events)
    else:
        return "Invalid input. Please specify 'good' or 'bad'."

    
# Example usage:
summary = holiday_summary('good')
print(summary)

# Generated by ChatGPT
# My original code was similar to this, but I had issues trying figure out about how to get the output.
