# Fully generated by ChatGPT 3.5, concept being ported over to a gui in `json_maker.py`

import json

def create_question_set(difficulty):
    questions = []
    print(f"Enter {difficulty} level questions and answers (type 'done' when finished):")
    while True:
        question = input("Enter question (or type 'done'): ")
        if question.lower() == 'done':
            break
        answer = input("Enter answer: ")
        questions.append([question, answer])
    return questions

def main():
    data = {}
    while True:
        difficulty = input("Enter difficulty level (type 'done' to finish): ")
        if difficulty.lower() == 'done':
            break
        data[difficulty] = create_question_set(difficulty)


    
    print("Questions saved to 'questions.json'.")

if __name__ == "__main__":
    main()
