# Convert mp4 to mp3
# THIS CODE IS Generated BY ChatGPT and Copliot
# Caution!: Need to install pydub(pip) and locate ffmpeg(exe) in the path

import os
from pydub import AudioSegment

folder_path = input("Enter the folder path: ")
folder_path = os.path.abspath(folder_path)

if os.path.exists(folder_path):
    for file in os.listdir(folder_path):
        if file.endswith(".mp4"):
            file_path = os.path.join(folder_path, file)
            if os.path.exists(file_path):
                audio = AudioSegment.from_file(file_path, format="mp4")
                out_path = os.path.join(folder_path, file.replace(".mp4", ".mp3"))
                audio.export(out_path, format="mp3")
                print(f"{file_path} converted to {out_path}")
else:
    print(f"{folder_path} does not exist.")